Add post for eurocast
prescriptiveanalytics/prescriptiveanalytics.github.io pull request #4
Opened 2024-03-11 12:16 UTC by falknerdominik

Please review and add pictures if wanted

2024-03-11 13:39 UTC, janzenisek approved these changes
perfect! thx!

2024-03-11 16:10 UTC, MichaelBoegl requested changes
Super geschrieben, kleine Anmerkung zum Teasertext.

2024-03-11 16:10 UTC, MichaelBoegl commented on _posts/2024-03-04-eurocast2024.md
> +Zwischen dem 25. Februar und dem 1. März 2024 wurde die 19. Eurocast, die internationale Konferenz zur computergestützten Systemtheorie, im Museo Elder de la Ciencia y la Tecnología in der nähe des P
Ich glaube "Nähe" schreibt man groß.

2024-03-12 11:04 UTC, falknerdominik commented on _posts/2024-03-04-eurocast2024.md
> +Zwischen dem 25. Februar und dem 1. März 2024 wurde die 19. Eurocast, die internationale Konferenz zur computergestützten Systemtheorie, im Museo Elder de la Ciencia y la Tecnología in der nähe des P
https://rechtschreibpruefung24.de/ stimmt dir zu. Wird geändert.

2024-03-12 11:10 UTC, MichaelBoegl approved these changes

2024-03-15 15:15 UTC, merged